project:
  type: website
  
website:
  title: "KJM Portfolio"
  navbar:
    right:
      - index.qmd
      - icon: github
        href: https://github.com/kerryjmartin
      - icon: linkedin
        href: https://linkedin.com/in/martin-kj
    left:
      - index.qmd
      - resume.qmd
      
format:
  html:
    theme: flatly
  


